### PR TITLE
Vertx 4 Compatibility

### PR DESCRIPTION
**Pull request by doctorpangloss**
- Removed CompleteableFuture and Async driver based generators
 - Added dependency to Jackson Databind
 - Fixed issues with JsonObject in RowMappers (shoddily)
 - Transaction API now returns a FailedFuture instead of throwing an IllegalStateException when not actually in a transaction
 - Tests improved for running on macOS

### CODE REVIEW

**Comment by doctorpangloss** [comment]
also if I were you I'd migrate to `testcontainers` and then you can run automated tests easier with Travis. I'm not good enough at Maven to set up the CI but it should be pretty easy.

**Comment by jklingsporn** [comment]
Wow, thank you very much for this. I will look into it as soon as I find the time. Because I am quite busy right now your PR is very welcome!

**Comment by jklingsporn** [comment]
> also if I were you I'd migrate to `testcontainers` and then you can run automated tests easier with Travis. I'm not good enough at Maven to set up the CI but it should be pretty easy.

Haven't worked with `testcontainers` yet, but it makes sense. Also setting up a build pipeline using github actions would improve testability.

**Comment by doctorpangloss** [comment]
Yep all tests pass for me. But you should look at this JsonObject / JsonArray workaround

**Comment by doctorpangloss** [comment]
It's all tested in production for me now, and looking good.

**Comment by jklingsporn** [comment]
Great stuff. Regarding the workaround: why was it necessary?

**Comment by jklingsporn** [comment]
What I mean is: when the defined type is, for example a `JsonObject`, why not just use `row.getJsonObject()`. And regarding your TODO-comment: I don't really remember the reason for bypassing the defined converters/bindings. We can probably leave it out.

**Comment by jklingsporn** [comment]
Also, can you please tick [`Allow edits from maintainers`](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) on the right hand side so I can push into this fork?

**Comment by doctorpangloss** [comment]
> Great stuff. Regarding the workaround: why was it necessary?

Not 100% sure. `getJsonObject` was being emitted for a `String`. It might be that I didn't generate the code correctly (I ran the `generateCode` test everywhere). It looks like something about `MySqlRowImpl` also has changed in 4.0.

**Comment by doctorpangloss** [comment]
I'm not sure why it's not showing the Allow edits from maintainers checkbox for me. I would check if if I saw it.

**Comment by jklingsporn** [comment]
I think I get it now. In the test database, the column is of type `varchar` and we define a converter for it. During code generation, it just checks for the desired user type (for example `JsonObject`) and assumes the database column is of the same type (which is wrong obviously). I'll fix it.

**Pull request merged**
